# Generated by Django 6.0.7 on 2026-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0002_humanlanguage_interviewer_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='tos_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the interviewer accepted the current ToS version', null=True),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='tos_accepted_version',
            field=models.CharField(blank=True, default='', help_text='Version of the Interviewer ToS this interviewer has accepted', max_length=20),
        ),
    ]
