# Generated by Django 6.0.7 on 2026-07-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0003_interviewer_tos_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='cal_event_type_id',
            field=models.CharField(blank=True, default='', help_text='Cal.com Event Type ID for booking. Profile is hidden from the public site until this is set.', max_length=100),
        ),
    ]
