# Generated by Django 6.0.7 on 2026-07-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0004_alter_interviewer_cal_event_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewer',
            old_name='cal_event_type_id',
            new_name='cal_link',
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='cal_link',
            field=models.CharField(blank=True, default='', help_text="Cal.com link for booking, e.g. 'username/event-slug'. Profile is hidden from the public site until this is set.", max_length=100),
        ),
    ]
