# Generated by Django 6.0.7 on 2026-08-13 08:24

from django.db import migrations, models


def grandfather_existing_interviewers(apps, schema_editor):
    """Approve every interviewer that already existed before self-service
    registration shipped -- they were already manually vetted and created
    via Django admin, so they shouldn't get locked out by the new gate."""
    Interviewer = apps.get_model('interviewers', 'Interviewer')
    Interviewer.objects.update(approval_status='approved')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0005_rename_cal_event_type_id_to_cal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', help_text='Whether this interviewer has been approved to use the platform.', max_length=20),
        ),
        migrations.RunPython(grandfather_existing_interviewers, noop),
    ]
